-- ============================================================
-- InvenTrack - Sistema de gestion de inventarios (PostgreSQL)
-- Sin CREATE DATABASE: ejecutar sobre la base ya creada
-- (pgAdmin local o la base que entrega Render).
-- IDs autogenerados con IDENTITY. Tras el esquema van los INSERT.
-- ============================================================

CREATE TABLE Categorias
(
  IDcategorias INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Nombre       VARCHAR(200) NULL,
  Descripcion  VARCHAR(100) NULL,
  PRIMARY KEY (IDcategorias)
);

CREATE TABLE Marcas
(
  IDmarca     INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Nombre      VARCHAR(100) NULL,
  Descripcion VARCHAR(200) NULL,
  Activo      BOOL         NULL,
  PRIMARY KEY (IDmarca)
);

CREATE TABLE Sucursales
(
  IDSucursal INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Nombre     VARCHAR(100) NULL,
  Direccion  VARCHAR(200) NULL,
  Telefono   VARCHAR(50)  NULL,
  Activo     BOOL         NULL,
  PRIMARY KEY (IDSucursal)
);

CREATE TABLE Usuario
(
  IDusuario     INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDSucursal    INT          NOT NULL,
  Nombre        VARCHAR(200) NULL,
  Correo        VARCHAR(100) NULL,
  Contrasena    VARCHAR(200) NULL,
  Rol           VARCHAR(20)  NULL,
  Acceso        TIMESTAMP    NULL,
  Activo        BOOL         NULL,
  FechaCreacion TIMESTAMP    NULL,
  PRIMARY KEY (IDusuario)
);

CREATE TABLE Producto
(
  IDproducto    INT           GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDcategorias  INT           NOT NULL,
  IDmarca       INT           NULL,
  Codigo        VARCHAR(50)   NULL,
  Nombre        VARCHAR(300)  NULL,
  Descripcion   VARCHAR(200)  NULL,
  PrecioVenta   DECIMAL(10,2) NULL,
  PrecioCosto   DECIMAL(10,2) NULL,
  StockMinimo   INT           NULL,
  Activo        BOOL          NULL,
  FechaCreacion TIMESTAMP     NULL,
  PRIMARY KEY (IDproducto)
);

CREATE TABLE Inventario
(
  IDinventario       INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDSucursal         INT          NOT NULL,
  IDproducto         INT          NOT NULL,
  CantidadDisponible INT          NULL,
  Ubicacion          VARCHAR(100) NULL,
  Actualizacion      TIMESTAMP    NULL,
  PRIMARY KEY (IDinventario)
);

CREATE TABLE Proveedores
(
  IDproveedor INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Nombre      VARCHAR(200) NULL,
  RFC_NIT     VARCHAR(50)  NULL,
  Telefono    VARCHAR(50)  NULL,
  Correo      VARCHAR(100) NULL,
  Direccion   VARCHAR(200) NULL,
  Activo      BOOL         NULL,
  PRIMARY KEY (IDproveedor)
);

CREATE TABLE Producto_proveedor
(
  IDproductoProveedor INT           GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDproducto          INT           NOT NULL,
  IDproveedor         INT           NOT NULL,
  CodigoProveedor     VARCHAR(100)  NULL,
  PrecioCompra        DECIMAL(10,2) NULL,
  Activo              BOOL          NULL,
  PRIMARY KEY (IDproductoProveedor)
);

CREATE TABLE Clientes
(
  IDcliente     INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Nombre        VARCHAR(200) NULL,
  Documento     VARCHAR(50)  NULL,
  Telefono      VARCHAR(50)  NULL,
  Correo        VARCHAR(100) NULL,
  Direccion     VARCHAR(200) NULL,
  FechaRegistro TIMESTAMP    NULL,
  PRIMARY KEY (IDcliente)
);

CREATE TABLE Metodos_pago
(
  IDmetodoPago INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Nombre       VARCHAR(50)  NULL,
  Descripcion  VARCHAR(150) NULL,
  Activo       BOOL         NULL,
  PRIMARY KEY (IDmetodoPago)
);

CREATE TABLE Ordenes_compra
(
  IDcompra    INT           GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDproveedor INT           NOT NULL,
  IDSucursal  INT           NOT NULL,
  IDusuario   INT           NOT NULL,
  FechaCompra TIMESTAMP     NULL,
  Total       DECIMAL(12,2) NULL,
  Estado      VARCHAR(20)   NULL,
  Observacion VARCHAR(300)  NULL,
  PRIMARY KEY (IDcompra)
);

CREATE TABLE Detalle_compra
(
  IDdetalleCompra INT           GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDcompra        INT           NOT NULL,
  IDproducto      INT           NOT NULL,
  Cantidad        INT           NULL,
  PrecioUnitario  DECIMAL(10,2) NULL,
  Subtotal        DECIMAL(12,2) NULL,
  PRIMARY KEY (IDdetalleCompra)
);

CREATE TABLE Ventas
(
  IDventa      INT           GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDcliente    INT           NOT NULL,
  IDSucursal   INT           NOT NULL,
  IDusuario    INT           NOT NULL,
  IDmetodoPago INT           NOT NULL,
  FechaVenta   TIMESTAMP     NULL,
  Total        DECIMAL(12,2) NULL,
  Estado       VARCHAR(20)   NULL,
  Observacion  VARCHAR(300)  NULL,
  PRIMARY KEY (IDventa)
);

CREATE TABLE Detalle_ventas
(
  IDdetalleVenta INT           GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDventa        INT           NOT NULL,
  IDproducto     INT           NOT NULL,
  Cantidad       INT           NULL,
  PrecioUnitario DECIMAL(10,2) NULL,
  Descuento      DECIMAL(12,2) NULL,
  Subtotal       DECIMAL(12,2) NULL,
  PRIMARY KEY (IDdetalleVenta)
);

CREATE TABLE Traslados
(
  IDtraslado        INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDSucursalOrigen  INT          NOT NULL,
  IDSucursalDestino INT          NOT NULL,
  IDusuario         INT          NOT NULL,
  FechaSolicitud    TIMESTAMP    NULL,
  FechaEnvio        TIMESTAMP    NULL,
  FechaRecepcion    TIMESTAMP    NULL,
  Estado            VARCHAR(20)  NULL,
  Observacion       VARCHAR(300) NULL,
  PRIMARY KEY (IDtraslado)
);

CREATE TABLE Detalle_traslado
(
  IDdetalleTraslado INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDtraslado        INT NOT NULL,
  IDproducto        INT NOT NULL,
  Cantidad          INT NULL,
  PRIMARY KEY (IDdetalleTraslado)
);

CREATE TABLE Movimiento_inventario
(
  IDMovimiento      INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDproducto        INT          NOT NULL,
  IDusuario         INT          NOT NULL,
  IDSucursal        INT          NOT NULL,
  IDdetalleCompra   INT          NULL,
  IDdetalleVenta    INT          NULL,
  IDdetalleTraslado INT          NULL,
  TipoMovimiento    VARCHAR(20)  NULL,
  Cantidad          INT          NULL,
  Motivo            VARCHAR(100) NULL,
  Fecha             TIMESTAMP    NULL,
  PRIMARY KEY (IDMovimiento)
);

-- ------------------------------------------------------------
-- Llaves foraneas
-- ------------------------------------------------------------
ALTER TABLE Usuario
  ADD CONSTRAINT FK_Sucursales_TO_Usuario
    FOREIGN KEY (IDSucursal) REFERENCES Sucursales (IDSucursal);

ALTER TABLE Producto
  ADD CONSTRAINT FK_Categorias_TO_Producto
    FOREIGN KEY (IDcategorias) REFERENCES Categorias (IDcategorias);

ALTER TABLE Producto
  ADD CONSTRAINT FK_Marcas_TO_Producto
    FOREIGN KEY (IDmarca) REFERENCES Marcas (IDmarca);

ALTER TABLE Inventario
  ADD CONSTRAINT FK_Sucursales_TO_Inventario
    FOREIGN KEY (IDSucursal) REFERENCES Sucursales (IDSucursal);

ALTER TABLE Inventario
  ADD CONSTRAINT FK_Producto_TO_Inventario
    FOREIGN KEY (IDproducto) REFERENCES Producto (IDproducto);

ALTER TABLE Producto_proveedor
  ADD CONSTRAINT FK_Producto_TO_Producto_proveedor
    FOREIGN KEY (IDproducto) REFERENCES Producto (IDproducto);

ALTER TABLE Producto_proveedor
  ADD CONSTRAINT FK_Proveedores_TO_Producto_proveedor
    FOREIGN KEY (IDproveedor) REFERENCES Proveedores (IDproveedor);

ALTER TABLE Ordenes_compra
  ADD CONSTRAINT FK_Proveedores_TO_Ordenes_compra
    FOREIGN KEY (IDproveedor) REFERENCES Proveedores (IDproveedor);

ALTER TABLE Ordenes_compra
  ADD CONSTRAINT FK_Sucursales_TO_Ordenes_compra
    FOREIGN KEY (IDSucursal) REFERENCES Sucursales (IDSucursal);

ALTER TABLE Ordenes_compra
  ADD CONSTRAINT FK_Usuario_TO_Ordenes_compra
    FOREIGN KEY (IDusuario) REFERENCES Usuario (IDusuario);

ALTER TABLE Detalle_compra
  ADD CONSTRAINT FK_Ordenes_compra_TO_Detalle_compra
    FOREIGN KEY (IDcompra) REFERENCES Ordenes_compra (IDcompra);

ALTER TABLE Detalle_compra
  ADD CONSTRAINT FK_Producto_TO_Detalle_compra
    FOREIGN KEY (IDproducto) REFERENCES Producto (IDproducto);

ALTER TABLE Ventas
  ADD CONSTRAINT FK_Clientes_TO_Ventas
    FOREIGN KEY (IDcliente) REFERENCES Clientes (IDcliente);

ALTER TABLE Ventas
  ADD CONSTRAINT FK_Sucursales_TO_Ventas
    FOREIGN KEY (IDSucursal) REFERENCES Sucursales (IDSucursal);

ALTER TABLE Ventas
  ADD CONSTRAINT FK_Usuario_TO_Ventas
    FOREIGN KEY (IDusuario) REFERENCES Usuario (IDusuario);

ALTER TABLE Ventas
  ADD CONSTRAINT FK_Metodos_pago_TO_Ventas
    FOREIGN KEY (IDmetodoPago) REFERENCES Metodos_pago (IDmetodoPago);

ALTER TABLE Detalle_ventas
  ADD CONSTRAINT FK_Ventas_TO_Detalle_ventas
    FOREIGN KEY (IDventa) REFERENCES Ventas (IDventa);

ALTER TABLE Detalle_ventas
  ADD CONSTRAINT FK_Producto_TO_Detalle_ventas
    FOREIGN KEY (IDproducto) REFERENCES Producto (IDproducto);

ALTER TABLE Traslados
  ADD CONSTRAINT FK_SucursalOrigen_TO_Traslados
    FOREIGN KEY (IDSucursalOrigen) REFERENCES Sucursales (IDSucursal);

ALTER TABLE Traslados
  ADD CONSTRAINT FK_SucursalDestino_TO_Traslados
    FOREIGN KEY (IDSucursalDestino) REFERENCES Sucursales (IDSucursal);

ALTER TABLE Traslados
  ADD CONSTRAINT FK_Usuario_TO_Traslados
    FOREIGN KEY (IDusuario) REFERENCES Usuario (IDusuario);

ALTER TABLE Detalle_traslado
  ADD CONSTRAINT FK_Traslados_TO_Detalle_traslado
    FOREIGN KEY (IDtraslado) REFERENCES Traslados (IDtraslado);

ALTER TABLE Detalle_traslado
  ADD CONSTRAINT FK_Producto_TO_Detalle_traslado
    FOREIGN KEY (IDproducto) REFERENCES Producto (IDproducto);

ALTER TABLE Movimiento_inventario
  ADD CONSTRAINT FK_Producto_TO_Movimiento_inventario
    FOREIGN KEY (IDproducto) REFERENCES Producto (IDproducto);

ALTER TABLE Movimiento_inventario
  ADD CONSTRAINT FK_Usuario_TO_Movimiento_inventario
    FOREIGN KEY (IDusuario) REFERENCES Usuario (IDusuario);

ALTER TABLE Movimiento_inventario
  ADD CONSTRAINT FK_Sucursales_TO_Movimiento_inventario
    FOREIGN KEY (IDSucursal) REFERENCES Sucursales (IDSucursal);

ALTER TABLE Movimiento_inventario
  ADD CONSTRAINT FK_Detalle_compra_TO_Movimiento_inventario
    FOREIGN KEY (IDdetalleCompra) REFERENCES Detalle_compra (IDdetalleCompra);

ALTER TABLE Movimiento_inventario
  ADD CONSTRAINT FK_Detalle_ventas_TO_Movimiento_inventario
    FOREIGN KEY (IDdetalleVenta) REFERENCES Detalle_ventas (IDdetalleVenta);

ALTER TABLE Movimiento_inventario
  ADD CONSTRAINT FK_Detalle_traslado_TO_Movimiento_inventario
    FOREIGN KEY (IDdetalleTraslado) REFERENCES Detalle_traslado (IDdetalleTraslado);

-- ============================================================
-- DATA DE PRUEBA
-- Los IDs no se insertan: los genera IDENTITY (1, 2, 3...) en el
-- orden de cada INSERT. Ejecutar sobre tablas recien creadas.
-- ============================================================

INSERT INTO Categorias (Nombre, Descripcion) VALUES
  ('Electronica',      'Equipos y accesorios electronicos'),
  ('Hogar',            'Articulos para el hogar'),
  ('Ferreteria',       'Herramientas y materiales'),
  ('Abarrotes',        'Alimentos y productos de consumo'),
  ('Utiles de oficina','Papeleria y utiles escolares');

INSERT INTO Marcas (Nombre, Descripcion, Activo) VALUES
  ('Samsung',       'Electronica de consumo',   TRUE),
  ('Philips',       'Iluminacion y audio',      TRUE),
  ('Truper',        'Herramientas manuales',    TRUE),
  ('Alicorp',       'Alimentos y consumo masivo', TRUE),
  ('Faber-Castell', 'Utiles de escritura',      TRUE);

INSERT INTO Sucursales (Nombre, Direccion, Telefono, Activo) VALUES
  ('Sucursal Lima Centro', 'Av. Abancay 123, Lima',          '01-4231001', TRUE),
  ('Sucursal Miraflores',  'Av. Larco 456, Miraflores',      '01-4452002', TRUE),
  ('Sucursal Arequipa',    'Calle Mercaderes 789, Arequipa', '054-203003', TRUE);

INSERT INTO Usuario (IDSucursal, Nombre, Correo, Contrasena, Rol, Acceso, Activo, FechaCreacion) VALUES
  (1, 'Carlos Admin',      'admin@inventrack.pe',      '$2a$10$/HnBiarFLqv3C.3WZ2MazexQYn5Ul4tWcF2s6cyE6ZfUq5HXqF.mS',   'Administrador',      NULL, TRUE, '2026-09-01 09:00:00'),
  (1, 'Lucia Vendedora',   'lucia@inventrack.pe',      '$2a$10$/HnBiarFLqv3C.3WZ2MazexQYn5Ul4tWcF2s6cyE6ZfUq5HXqF.mS',  'Vendedor',   NULL, TRUE, '2026-09-01 09:10:00'),
  (2, 'Mario Vendedor',    'mario@inventrack.pe',      '$2a$10$/HnBiarFLqv3C.3WZ2MazexQYn5Ul4tWcF2s6cyE6ZfUq5HXqF.mS',  'Vendedor',   NULL, TRUE, '2026-09-01 09:20:00'),
  (2, 'Rosa Almacenera',   'rosa@inventrack.pe',       '$2a$10$/HnBiarFLqv3C.3WZ2MazexQYn5Ul4tWcF2s6cyE6ZfUq5HXqF.mS', 'Almacen', NULL, TRUE, '2026-09-01 09:30:00'),
  (3, 'Jorge Vendedor',    'jorge@inventrack.pe',      '$2a$10$/HnBiarFLqv3C.3WZ2MazexQYn5Ul4tWcF2s6cyE6ZfUq5HXqF.mS',  'Vendedor',   NULL, TRUE, '2026-09-01 09:40:00');

INSERT INTO Producto (IDcategorias, IDmarca, Codigo, Nombre, Descripcion, PrecioVenta, PrecioCosto, StockMinimo, Activo, FechaCreacion) VALUES
  (1, 1, 'ELEC-001', 'Televisor Samsung 43"',      'Smart TV 43 pulgadas',        1299.00, 950.00,  5, TRUE, '2026-09-02 10:00:00'),
  (2, 2, 'HOG-001',  'Foco LED Philips 12W',       'Luz blanca 12W',                12.50,   7.00, 50, TRUE, '2026-09-02 10:05:00'),
  (3, 3, 'FER-001',  'Taladro Truper 1/2"',        'Taladro percutor',             189.90, 130.00,  5, TRUE, '2026-09-02 10:10:00'),
  (4, 4, 'ABA-001',  'Aceite Primor 1L',           'Aceite vegetal botella 1L',      9.50,   7.20, 40, TRUE, '2026-09-02 10:15:00'),
  (5, 5, 'UTI-001',  'Lapices Faber-Castell x12',  'Caja de 12 lapices',            18.00,  11.00, 20, TRUE, '2026-09-02 10:20:00'),
  (1, 2, 'ELEC-002', 'Parlante Philips Bluetooth', 'Parlante portatil',            149.00,  95.00,  8, TRUE, '2026-09-02 10:25:00'),
  (3, 3, 'FER-002',  'Martillo Truper',            'Martillo de acero 16 oz',       35.00,  22.00, 10, TRUE, '2026-09-02 10:30:00'),
  (4, 4, 'ABA-002',  'Fideos Don Vittorio 500g',   'Fideos spaghetti 500g',          3.80,   2.60, 60, TRUE, '2026-09-02 10:35:00'),
  (5, 5, 'UTI-002',  'Cuaderno A4 cuadriculado',   'Cuaderno 100 hojas',             7.50,   4.20, 30, TRUE, '2026-09-02 10:40:00'),
  (2, 2, 'HOG-002',  'Enchufe inteligente Philips','Smart plug WiFi',               45.00,  28.00, 10, TRUE, '2026-09-02 10:45:00');

INSERT INTO Inventario (IDSucursal, IDproducto, CantidadDisponible, Ubicacion, Actualizacion) VALUES
  (1, 1,  9, 'Pasillo A-1', '2026-09-10 12:00:00'),
  (1, 6,  8, 'Pasillo A-2', '2026-09-10 12:00:00'),
  (1, 4, 30, 'Pasillo C-1', '2026-09-10 12:00:00'),
  (1, 8, 60, 'Pasillo C-2', '2026-09-10 12:00:00'),
  (2, 3,  9, 'Pasillo B-1', '2026-09-10 12:00:00'),
  (2, 7, 18, 'Pasillo B-2', '2026-09-10 12:00:00'),
  (2, 2, 40, 'Pasillo D-1', '2026-09-10 12:00:00'),
  (3, 5, 25, 'Pasillo E-1', '2026-09-10 12:00:00'),
  (3, 9, 40, 'Pasillo E-2', '2026-09-10 12:00:00'),
  (3, 10,15, 'Pasillo D-2', '2026-09-10 12:00:00');

INSERT INTO Proveedores (Nombre, RFC_NIT, Telefono, Correo, Direccion, Activo) VALUES
  ('Distribuidora Electro Peru SAC', '20512345678', '01-6001001', 'ventas@electroperu.pe', 'Av. Industrial 100, Lima',   TRUE),
  ('Ferreteria Mayorista Truper',    '20587654321', '01-6002002', 'pedidos@truper.pe',      'Jr. Comercio 200, Lima',     TRUE),
  ('Alimentos y Consumo del Sur SAC','20598765432', '054-607003', 'compras@consumosur.pe',  'Av. Parra 300, Arequipa',    TRUE);

INSERT INTO Producto_proveedor (IDproducto, IDproveedor, CodigoProveedor, PrecioCompra, Activo) VALUES
  (1, 1, 'EP-TV43',  950.00, TRUE),
  (6, 1, 'EP-PARL',   95.00, TRUE),
  (10,1, 'EP-SPLUG',  28.00, TRUE),
  (3, 2, 'TR-TAL12', 130.00, TRUE),
  (7, 2, 'TR-MART',   22.00, TRUE),
  (4, 3, 'CS-ACE1',    7.20, TRUE),
  (8, 3, 'CS-FID5',    2.60, TRUE),
  (9, 3, 'CS-CUA4',    4.20, TRUE);

INSERT INTO Clientes (Nombre, Documento, Telefono, Correo, Direccion, FechaRegistro) VALUES
  ('Ana Torres Quispe',     '45678912', '987654321', 'ana.torres@correo.pe',    'Jr. Union 10, Lima',        '2026-09-03 11:00:00'),
  ('Bodega San Martin EIRL','20601234567','986543210','bodega.sanmartin@correo.pe','Av. Brasil 55, Lima',      '2026-09-03 11:10:00'),
  ('Luis Paredes Rojas',    '41237856', '985432109', 'luis.paredes@correo.pe',  'Calle Los Pinos 8, Miraflores','2026-09-03 11:20:00'),
  ('Marta Flores Huaman',   '47891234', '984321098', 'marta.flores@correo.pe',  'Av. Ejercito 90, Arequipa', '2026-09-03 11:30:00'),
  ('Cliente Mostrador',     '00000000', NULL,        NULL,                      NULL,                        '2026-09-03 11:40:00');

INSERT INTO Metodos_pago (Nombre, Descripcion, Activo) VALUES
  ('Efectivo',      'Pago en efectivo',            TRUE),
  ('Tarjeta',       'Tarjeta de debito o credito', TRUE),
  ('Yape',          'Pago con billetera digital',  TRUE),
  ('Transferencia', 'Transferencia bancaria',      TRUE);

INSERT INTO Ordenes_compra (IDproveedor, IDSucursal, IDusuario, FechaCompra, Total, Estado, Observacion) VALUES
  (1, 1, 1, '2026-09-05 10:00:00', 10450.00, 'Recibida',  'Reposicion de electronica'),
  (2, 2, 4, '2026-09-05 11:00:00',  1740.00, 'Recibida',  'Reposicion de ferreteria'),
  (3, 1, 1, '2026-09-08 09:00:00',  1240.00, 'Pendiente', 'Pedido de abarrotes');

INSERT INTO Detalle_compra (IDcompra, IDproducto, Cantidad, PrecioUnitario, Subtotal) VALUES
  (1, 1,  10, 950.00, 9500.00),
  (1, 6,  10,  95.00,  950.00),
  (2, 3,  10, 130.00, 1300.00),
  (2, 7,  20,  22.00,  440.00),
  (3, 4, 100,   7.20,  720.00),
  (3, 8, 200,   2.60,  520.00);

INSERT INTO Ventas (IDcliente, IDSucursal, IDusuario, IDmetodoPago, FechaVenta, Total, Estado, Observacion) VALUES
  (1, 1, 2, 1, '2026-09-09 15:00:00', 1597.00, 'Registrada', 'Venta de electronica'),
  (2, 2, 3, 3, '2026-09-09 16:00:00',  254.90, 'Registrada', 'Venta de ferreteria'),
  (3, 1, 2, 2, '2026-09-10 10:00:00',   85.50, 'Registrada', 'Venta de abarrotes'),
  (4, 3, 5, 1, '2026-09-10 11:00:00',   50.00, 'Registrada', 'Venta de utiles');

INSERT INTO Detalle_ventas (IDventa, IDproducto, Cantidad, PrecioUnitario, Descuento, Subtotal) VALUES
  (1, 1, 1, 1299.00, 0.00, 1299.00),
  (1, 6, 2,  149.00, 0.00,  298.00),
  (2, 3, 1,  189.90, 0.00,  189.90),
  (2, 7, 2,   35.00, 5.00,   65.00),
  (3, 4, 5,    9.50, 0.00,   47.50),
  (3, 8,10,    3.80, 0.00,   38.00),
  (4, 5, 3,   18.00, 4.00,   50.00);

-- Contrasena de todos los usuarios de prueba: ClaveSegura2026* (BCrypt)
-- Traslados: tabla presente en la BD, fuera del alcance del Sprint 1
INSERT INTO Traslados (IDSucursalOrigen, IDSucursalDestino, IDusuario, FechaSolicitud, FechaEnvio, FechaRecepcion, Estado, Observacion) VALUES
  (1, 2, 1, '2026-09-11 09:00:00', NULL, NULL, 'Pendiente', 'Traslado de televisores a Miraflores');

INSERT INTO Detalle_traslado (IDtraslado, IDproducto, Cantidad) VALUES
  (1, 1, 2);

INSERT INTO Movimiento_inventario (IDproducto, IDusuario, IDSucursal, IDdetalleCompra, IDdetalleVenta, IDdetalleTraslado, TipoMovimiento, Cantidad, Motivo, Fecha) VALUES
  (1, 1, 1, 1,    NULL, NULL, 'Entrada', 10, 'Compra',  '2026-09-06 10:00:00'),
  (6, 1, 1, 2,    NULL, NULL, 'Entrada', 10, 'Compra',  '2026-09-06 10:00:00'),
  (3, 4, 2, 3,    NULL, NULL, 'Entrada', 10, 'Compra',  '2026-09-06 11:00:00'),
  (7, 4, 2, 4,    NULL, NULL, 'Entrada', 20, 'Compra',  '2026-09-06 11:00:00'),
  (1, 2, 1, NULL, 1,    NULL, 'Salida',   1, 'Venta',            '2026-09-09 15:00:00'),
  (6, 2, 1, NULL, 2,    NULL, 'Salida',   2, 'Venta',            '2026-09-09 15:00:00'),
  (3, 3, 2, NULL, 3,    NULL, 'Salida',   1, 'Venta',            '2026-09-09 16:00:00'),
  (7, 3, 2, NULL, 4,    NULL, 'Salida',   2, 'Venta',            '2026-09-09 16:00:00');
